spring.application.name=gestao_ocorrencias

# Configurações do Banco H2 trocar para variavel de ambiente
spring.datasource.url=jdbc:postgresql://localhost:5432/ocorrenciasdb
spring.datasource.username=sa
spring.datasource.password=postgrespassword
spring.datasource.driver-class-name=org.postgresql.Driver

#database config
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration



# Mapeamento do Swagger e OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

api.security.token.secret=${API_SECURITY_TOKEN_SECRET:minha-chave-secreta-padrao-para-dev-123456}

logging.level.org.flywaydb=DEBUG