spring.application.name=gestao_ocorrencias

# Configurações do Banco H2
spring.datasource.url=jdbc:h2:mem:ocorrenciasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativa o console do H2 no navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Atualiza o banco automaticamente com base nas suas entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mapeamento do Swagger e OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

api.security.token.secret=${API_SECURITY_TOKEN_SECRET:minha-chave-secreta-padrao-para-dev-123456}