spring.application.name=gestao_ocorrencias

# Configurações do Banco H2
spring.datasource.url=jdbc:h2:mem:ocorrenciasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativa o console do H2 no navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Atualiza o banco automaticamente com base nas suas entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Altera a rota padrão do HTML do Swagger (Acesso no navegador)
springdoc.swagger-ui.path=/swagger

# Altera a rota que gera o JSON bruto do OpenAPI (Caso precise exportar)
springdoc.api-docs.path=/api-docs